# Generated by Django 4.2 on 2023-04-20 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('is_published', models.BooleanField(verbose_name='Опубликован в шапке')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('currency', models.CharField(max_length=255, verbose_name='Валюта')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('size_height', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Высота товара')),
                ('size_width', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Ширина товара')),
                ('description_content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('new_product', models.BooleanField(verbose_name='Новинка')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower.category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['time_create', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('is_published', models.BooleanField(verbose_name='Опубликован в шапке')),
            ],
            options={
                'verbose_name': 'Повод',
                'verbose_name_plural': 'Поводы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('is_published', models.BooleanField(verbose_name='Опубликован в шапке')),
            ],
            options={
                'verbose_name': 'Время года',
                'verbose_name_plural': 'Времена года',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('is_published', models.BooleanField(verbose_name='Опубликован в шапке')),
            ],
            options={
                'verbose_name': 'Тип товара',
                'verbose_name_plural': 'Типы товаров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wrapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrapping_part_1', models.CharField(max_length=255, verbose_name='1 часть упаковки')),
                ('wrapping_part_2', models.CharField(max_length=255, verbose_name='2 часть упаковки')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower.flower', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Состав упаковки',
                'verbose_name_plural': 'Состав упаковки',
                'ordering': ['flower'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(verbose_name='Оценка товара')),
                ('review_description', models.TextField(blank=True, verbose_name='Описание отзыва')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower.flower', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['time_create', 'mark'],
            },
        ),
        migrations.AddField(
            model_name='flower',
            name='maturation_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.season', verbose_name='Время созревания'),
        ),
        migrations.AddField(
            model_name='flower',
            name='reason_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.occasion', verbose_name='Повод'),
        ),
        migrations.AddField(
            model_name='flower',
            name='type_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.type', verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_part_1', models.CharField(max_length=255, verbose_name='1 часть товара')),
                ('flower_part_2', models.CharField(max_length=255, verbose_name='2 часть товара')),
                ('flower_part_3', models.CharField(max_length=255, verbose_name='3 часть товара')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower.flower', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Состав букета',
                'verbose_name_plural': 'Состав букета',
                'ordering': ['flower'],
            },
        ),
    ]
