# Generated by Django 3.2.18 on 2023-04-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_auto_20230417_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='new_product',
            field=models.BooleanField(default=True, verbose_name='Новинка'),
            preserve_default=False,
        ),
    ]
