# Generated by Django 4.2 on 2023-04-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '1. Категория', 'verbose_name_plural': '1. Категории'},
        ),
        migrations.AlterModelOptions(
            name='composition',
            options={'ordering': ['flower'], 'verbose_name': '2. Состав букета', 'verbose_name_plural': '2. Состав букета'},
        ),
        migrations.AlterModelOptions(
            name='flower',
            options={'ordering': ['time_create', 'title'], 'verbose_name': '1. Товар', 'verbose_name_plural': '1. Товары'},
        ),
        migrations.AlterModelOptions(
            name='infoclass',
            options={'ordering': ['id'], 'verbose_name': '3. Класс инфо-страницы', 'verbose_name_plural': '3. Класс инфо-страниц'},
        ),
        migrations.AlterModelOptions(
            name='infopages',
            options={'ordering': ['id'], 'verbose_name': '3. Инфо-страница', 'verbose_name_plural': '3. Инфо-страницы'},
        ),
        migrations.AlterModelOptions(
            name='occasion',
            options={'ordering': ['name'], 'verbose_name': '1. Повод', 'verbose_name_plural': '1. Поводы'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['time_create', 'grade'], 'verbose_name': '2. Отзыв', 'verbose_name_plural': '2. Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['name'], 'verbose_name': '1. Время года', 'verbose_name_plural': '1. Времена года'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['name'], 'verbose_name': '1. Тип товара', 'verbose_name_plural': '1. Типы товаров'},
        ),
        migrations.AlterModelOptions(
            name='wrapping',
            options={'ordering': ['flower'], 'verbose_name': '2. Состав упаковки', 'verbose_name_plural': '2. Состав упаковки'},
        ),
    ]
