# Generated by Django 4.2 on 2023-04-25 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0003_alter_category_options_alter_composition_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название страницы')),
                ('path', models.CharField(max_length=255, verbose_name='Путь страницы')),
                ('order', models.IntegerField(verbose_name='Очередь столбца')),
                ('classificate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.infoclass', verbose_name='Класс')),
            ],
            options={
                'verbose_name': '4. Пользователь',
                'verbose_name_plural': '4. Пользователи',
                'ordering': ['id'],
            },
        ),
    ]
