# Generated by Django 3.2.18 on 2023-04-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0003_flower_new_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='occasion',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован в шапке'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован в шапке'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован в шапке'),
            preserve_default=False,
        ),
    ]
