# Generated by Django 3.2.18 on 2023-04-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0004_auto_20230418_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован в шапке'),
            preserve_default=False,
        ),
    ]
