# Generated by Django 4.2 on 2023-04-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0004_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='classificate',
        ),
        migrations.RemoveField(
            model_name='users',
            name='order',
        ),
        migrations.RemoveField(
            model_name='users',
            name='path',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='data', max_length=255, verbose_name='Логин'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='data', max_length=255, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
