# Generated by Django 4.2 on 2023-04-21 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0005_infopages'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Класс инфо-страницы',
                'verbose_name_plural': 'Класс инфо-страниц',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='infopages',
            options={'ordering': ['id'], 'verbose_name': 'Инфо-страница', 'verbose_name_plural': 'Инфо-страницы'},
        ),
        migrations.AddField(
            model_name='infopages',
            name='classificate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.infoclass', verbose_name='Класс'),
        ),
    ]
