# Generated by Django 4.2 on 2023-04-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0005_remove_users_classificate_remove_users_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='Логин'),
        ),
    ]
