# Generated by Django 4.2 on 2023-04-22 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0006_infoclass_alter_infopages_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopages',
            name='classificate',
        ),
        migrations.RemoveField(
            model_name='infopages',
            name='order',
        ),
        migrations.AddField(
            model_name='infoclass',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.infopages', verbose_name='Группа инфо-ссылок'),
        ),
    ]
