# Generated by Django 4.2 on 2023-04-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0007_rename_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': '4. Форма регистрации',
                'verbose_name_plural': '4. Форма регистрации',
                'ordering': ['id'],
            },
        ),
    ]
