# Generated by Django 4.2 on 2023-04-22 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0007_remove_infopages_classificate_remove_infopages_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoclass',
            name='group',
        ),
        migrations.AddField(
            model_name='infopages',
            name='classificate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.infoclass', verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='infopages',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Очередь столбца'),
            preserve_default=False,
        ),
    ]
