# Generated by Django 4.2 on 2023-04-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0008_register_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_form',
            old_name='password',
            new_name='password_first',
        ),
        migrations.AddField(
            model_name='register_form',
            name='password_second',
            field=models.CharField(default='', max_length=255, verbose_name='Повтор пароля'),
            preserve_default=False,
        ),
    ]
