# Generated by Django 4.2 on 2023-04-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0008_remove_infoclass_group_infopages_classificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoclass',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Очередь столбца'),
            preserve_default=False,
        ),
    ]
