# Generated by Django 4.2 on 2023-04-22 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0009_infoclass_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoclass',
            name='order',
        ),
    ]
