# Generated by Django 4.2 on 2023-04-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0010_remove_infoclass_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoclass',
            name='name_code',
            field=models.CharField(default='about', max_length=255, verbose_name='Код группы'),
            preserve_default=False,
        ),
    ]
