# Generated by Django 4.2 on 2023-04-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0011_infoclass_name_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['time_create', 'grade'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='mark',
            new_name='grade',
        ),
    ]
