# Generated by Django 4.2 on 2023-04-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0011_selectedproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectedproducts',
            options={'ordering': ['id'], 'verbose_name': '5. Список выбранных товаров', 'verbose_name_plural': '5. Список выбранных товаров'},
        ),
        migrations.AlterField(
            model_name='selectedproducts',
            name='sesseion_id',
            field=models.CharField(max_length=255, verbose_name='Код сессии'),
        ),
    ]
