# Generated by Django 4.2 on 2023-04-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0012_alter_selectedproducts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='count',
            field=models.IntegerField(verbose_name='Кол-во товара на складе'),
        ),
    ]
