# Generated by Django 4.2 on 2023-04-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0013_alter_flower_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedproducts',
            name='sesseion_id',
        ),
    ]
