# Generated by Django 4.2 on 2023-04-27 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0014_remove_selectedproducts_sesseion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedproducts',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
    ]
