# Generated by Django 4.2 on 2023-04-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0016_purchasedproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_form',
            old_name='email',
            new_name='email_register_field',
        ),
        migrations.RenameField(
            model_name='register_form',
            old_name='name',
            new_name='name_register_field',
        ),
        migrations.RenameField(
            model_name='register_form',
            old_name='password_first',
            new_name='password_first_register_field',
        ),
        migrations.RenameField(
            model_name='register_form',
            old_name='password_second',
            new_name='password_second_register_field',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='email_user_field',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='name_user_field',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password_user_field',
        ),
    ]
