# Generated by Django 4.2 on 2023-05-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0018_delete_register_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city_user_field',
            field=models.CharField(max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_user_field',
            field=models.CharField(max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname_user_field',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия'),
        ),
    ]
