# Generated by Django 4.2 on 2023-05-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0019_user_city_user_field_user_phone_user_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='userPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название страницы')),
                ('alter_name', models.CharField(max_length=255, verbose_name='Код страницы')),
            ],
            options={
                'verbose_name': '6. Пользовательская страница',
                'verbose_name_plural': '6. Список пользовательских страниц',
                'ordering': ['id'],
            },
        ),
    ]
