# Generated by Django 4.2 on 2023-05-15 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0021_user_sessionunqid'),
    ]

    operations = [
        migrations.CreateModel(
            name='likedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower.flower', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': '5. Список понравившихся товаров',
                'verbose_name_plural': '5. Понравившиеся товаров',
                'ordering': ['id'],
            },
        ),
    ]
