# Generated by Django 4.2 on 2023-05-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0022_likedproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedproducts',
            options={'ordering': ['id'], 'verbose_name': '5. Список понравившихся товаров', 'verbose_name_plural': '5. Понравившиеся товары'},
        ),
        migrations.AddField(
            model_name='purchasedproducts',
            name='status',
            field=models.CharField(default='0', max_length=255, verbose_name='статус заказа'),
            preserve_default=False,
        ),
    ]
