# Generated by Django 4.2 on 2023-05-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0023_alter_likedproducts_options_purchasedproducts_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Статус заказа')),
                ('code', models.IntegerField(verbose_name='Код статуса')),
            ],
            options={
                'verbose_name': '6. Статус заказа',
                'verbose_name_plural': '6. Статусы заказов',
                'ordering': ['id'],
            },
        ),
    ]
