# Generated by Django 4.2 on 2023-05-18 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0024_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedproducts',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower.orderstatus', verbose_name='статус заказа'),
        ),
    ]
