# Generated by Django 4.2 on 2023-05-22 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0026_cities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'ordering': ['id', 'name'], 'verbose_name': '2. Список доступных городов', 'verbose_name_plural': '2. Доступные города'},
        ),
        migrations.AlterField(
            model_name='user',
            name='city_user_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.cities', verbose_name='Город'),
        ),
    ]
