# Generated by Django 4.2 on 2023-05-23 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0028_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedproducts',
            name='order_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.order', verbose_name='Данные заказа'),
        ),
    ]
