# Generated by Django 4.2 on 2023-05-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0029_selectedproducts_order_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.CharField(default='0', max_length=255, verbose_name='Адрес доставки'),
            preserve_default=False,
        ),
    ]
