# Generated by Django 4.2 on 2023-05-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0031_rename_order_num_selectedproducts_order_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_address',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(null=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(null=True, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver_additional_info',
            field=models.CharField(max_length=255, null=True, verbose_name='Доп. информация для доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver_phone',
            field=models.CharField(max_length=255, null=True, verbose_name='Телефон получателя'),
        ),
    ]
