# Generated by Django 4.2 on 2023-05-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0032_alter_order_order_address_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sender_email',
            field=models.CharField(max_length=255, null=True, verbose_name='Email отправителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender_phone',
            field=models.CharField(max_length=255, null=True, verbose_name='Телефон отправителя'),
        ),
    ]
