# Generated by Django 4.2 on 2023-05-24 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0035_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedproducts',
            name='order_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.order', verbose_name='Данные заказа'),
        ),
    ]
