# Generated by Django 4.2 on 2023-05-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0036_purchasedproducts_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedproducts',
            name='pay_method',
            field=models.CharField(max_length=255, null=True, verbose_name='Метод оплаты'),
        ),
    ]
