# Generated by Django 4.2 on 2023-05-24 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0037_purchasedproducts_pay_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='flower',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.occasion', verbose_name='Автор отзыва'),
        ),
    ]
