# Generated by Django 4.2 on 2023-05-24 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0038_rename_flower_review_product_alter_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.user', verbose_name='Автор отзыва'),
        ),
    ]
