# Generated by Django 3.2.18 on 2023-04-17 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='maturation_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.season', verbose_name='Время созревания'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='reason_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.occasion', verbose_name='Повод'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='type_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.type', verbose_name='Тип'),
        ),
    ]
